[package]
name = "lang_impl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.0"
num = "0.4.0"
pest = "2.1.3"
pest_derive = "2.1.0"