[package]
name = "quip-interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
pad = "0.1.6"

[dev-dependencies]
pretty_assertions = "1.3.0"
